meta:
  title: Checkout API Reference (POC)
  description: The best API documentation generator ever.
  siteUrl: https://portal-demo.redoc.ly
headerIcon: ./images/logo.svg
enableToc: true
oasDefinitions:
  petstore: ./openapi/petstore.yaml
  checkout: ./openapi/swagger.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto:300,400,600,700
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
#ga:
  # you can use any options here from https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/
  # note that GA doesn't work in DEV
#  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:
  - search: true

  - label: Training exercises
    page: developer-portal/index.md

  - label: External docs
    href: https://docs.checkout.com/test-12345678


footer:
  copyrightText: Pretty footer goes here
